# Generated by Django 5.2.6 on 2025-10-04 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.BooleanField(default=False)),
                ('old_content', models.TextField(max_length=5000)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited', to='messaging.message')),
            ],
        ),
    ]
